src/Entity/Artikel.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArtikelRepository")
 */
class Artikel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $judul;

    /**
     * @ORM\Column(type="text")
     */
    private $isi;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $foto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $jenis;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lolos_edit;

        /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Penulis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $penulis;

    /**
     * @ORM\Column(type="integer")
     */
    private $counter;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getJudul(): ?string
    {
        return $this->judul;
    }

    public function setJudul(string $judul): self
    {
        $this->judul = $judul;

        return $this;
    }

    public function getIsi(): ?string
    {
        return $this->isi;
    }

    public function setIsi(string $isi): self
    {
        $this->isi = $isi;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }

    public function getJenis(): ?string
    {
        return $this->jenis;
    }

    public function setJenis(string $jenis): self
    {
        $this->jenis = $jenis;

        return $this;
    }

    public function getLolosEdit(): ?string
    {
        return $this->lolos_edit;
    }

    public function setLolosEdit(string $lolos_edit): self
    {
        $this->lolos_edit = $lolos_edit;

        return $this;
    }

    public function getCounter(): ?int
    {
        return $this->counter;
    }

    public function setCounter(int $counter): self
    {
        $this->counter = $counter;

        return $this;
    }

    public function getIdPenulis(): ?Penulis
    {
        return $this->penulis;
    }

    public function setIdPenulis(?Penulis $penulis): self
    {
        $this->penulis = $penulis;

        return $this;
    }
}

src/Form/ArtikelType.php
<?php

namespace App\Form;

use App\Entity\Artikel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtikelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('judul')
            ->add('isi')
            ->add('foto')
            ->add('jenis')
            ->add('lolos_edit')
            ->add('counter')
            ->add('id_penulis')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Artikel::class,
        ]);
    }
}

src/Controller/ArtikelController.php
<?php

namespace App\Controller;

use App\Entity\Artikel;
use App\Entity\Penulis;
use App\Form\ArtikelType;
use App\Repository\ArtikelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @Route("/artikel")
 */
class ArtikelController extends AbstractController
{
    /**
     * @Route("/", name="artikel_index", methods="GET")
     */
    public function index(ArtikelRepository $artikelRepository): Response
    {
        return $this->render('artikel/index.html.twig', ['artikels' => $artikelRepository->findAll()]);
    }

    /**
     * @Route("/new", name="artikel_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $repository = $this->getDoctrine()->getRepository(Penulis::class);
        $penulis = $repository->findAll();

        return $this->render('artikel/new.html.twig', [
            'penulis' => $penulis,
        ]);
    }

    /**
     * @Route("/{id}", name="artikel_show", methods="GET")
     */
    public function show(Artikel $artikel, $id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $art = $em->getRepository(Artikel::class)
            ->find($id);
        $art->setCounter(($art->getCounter()+1));
        $em->flush();
        return $this->render('artikel/show.html.twig', ['artikel' => $artikel]);
    }

    /**
     * @Route("/{id}/edit", name="artikel_edit", methods="GET|POST")
     */
    public function edit(Request $request, $id): Response
    {
        $repositoryp = $this->getDoctrine()->getRepository(Penulis::class);
        $repositorya = $this->getDoctrine()->getRepository(Artikel::class);
        $artikel = $repositorya->find($id);
        $penulis = $repositoryp->findAll();

        $form = $this->createForm(ArtikelType::class, $artikel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('artikel_edit', ['id' => $artikel->getId()]);
        }

        return $this->render('artikel/edit.html.twig', [
            'artikel' => $artikel,
            'penulis' => $penulis,
        ]);
    }

    /**
     * @Route("/{id}", name="artikel_delete", methods="DELETE")
     */
    public function delete(Request $request, Artikel $artikel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artikel->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $repository = $em->getRepository(Artikel::class);
            $data = $repository->find($artikel->getId());
            if(!unlink($data->getFoto())){
                echo "yeyek";
                die();
            }
            $em->remove($artikel);
            $em->flush();
        }

        return $this->redirectToRoute('artikel_index');
    }

    /**
     * @Route("/create", name="artikel_create", methods={"POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function create(Request $request)
    {
        $data = $request->request->all();
        $data['foto'] = $request->files->get('foto');

        $errors = Validation::createValidator()->validate($data, new Assert\Collection([
            'judul' => new Assert\NotBlank(['message' => 'Nama barang tidak boleh kosong']),
            'isi' => new Assert\NotBlank(['message' => 'Pilih Prodi']),
            'jenis' => new Assert\NotBlank(['message' => 'Alamat tidak boleh kosong']),
            'penulis' => new Assert\NotBlank(['message' => 'NIM tidak boleh kosong']),
            'lolos_edit' => new Assert\NotBlank(['message' => 'Pilih Jenis Kelamin']),
            'foto' => new Assert\NotBlank(['message' => 'Foto tidak boleh kosong']),
            'foto' => new Assert\Image()
        ]));

        if ($errors->count()>0)
        {
            var_dump($data);
            foreach ($errors as $error){
                print $error->getMessage()."<br>";
            }
            die();
        }
        else
        {
            $cek_artikel = $this->getDoctrine()
                ->getRepository(Artikel::class)
                ->findBy(['judul' => $request->get('judul')]);

            if (empty($cek_artikel)){
                $em = $this->getDoctrine()->getManager();

                $artikel = new Artikel();

                if (!empty($data['foto'])){
                    if (file_exists($path = '/images/' . $artikel->getFoto())) {
                        unlink($path);
                    }

                    $foto = $request->files->get('foto');
                    $foto->move('images', $foto->getClientOriginalName());

                    $artikel->setFoto('images/'.$foto->getClientOriginalName());
                }

                $penulis = $this->getDoctrine()
                    ->getRepository(Penulis::class)
                    ->find($request->get('penulis'));


                $artikel->setJudul($request->get('judul'));
                $artikel->setIdPenulis($penulis);
                $artikel->setIsi($request->get('isi'));
                $artikel->setCounter(0);
                $artikel->setJenis($request->get('jenis'));
                $artikel->setLolosEdit($request->get('lolos_edit'));

                $em->persist($artikel);
                $em->flush();

                $this->addFlash('success', "Berhasil menambahkan Artikel {$request->get('judul')}");

                return $this->redirectToRoute('artikel_index');
            }
            $this->addFlash('error',"Artikel yang berjudul {$request->get('judul')} telah ada");
        }
        return $this->redirectToRoute('artikel_index');
    }

    /**
     * @Route("/artikel/update", name="artikel_update", methods={"POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function update(Request $request){

        $em = $this->getDoctrine()->getManager();

        $artikel = $em->getRepository(Artikel::class)
            ->find($request->get('id'));

        if (!$artikel){
            $this->addFlash('error', "Artikel yang berjudul {$request->get('judul')} tidak ditemukan");

            return $this->redirectToRoute('artikel');
        }

        if (!empty($data['foto'])){
            if (file_exists($path = '/foto/' . $artikel->getFoto())) {
                unlink($path);
            }

            $foto = $request->files->get('foto');
            $foto->move('foto', $foto->getClientOriginalName());

            $artikel->setFoto($foto->getClientOriginalName());
        }

        $penulis = $this->getDoctrine()
            ->getRepository(Penulis::class)
            ->find($request->get('penulis_id'));


        $artikel->setJudul($request->get('judul'));
        $artikel->setPenulisId($penulis);
        $artikel->setJenis($request->get('jenis'));
        $artikel->setIsi($request->get('isi'));
        $artikel->setLolosEdit($request->get('lolos_edit'));

        $em->flush();

        $this->addFlash('success', "Berhasil memperbarui data artikel");

        return $this->redirectToRoute('artikel');
    }
}

templates/artikel/_delete_form.html.twig
<form method="post" action="{{ path('artikel_delete', {'id': artikel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artikel.id) }}">
    <button class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
</form>

templates/artikel/_form.html.twig
{# {{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

<div class="container mt-3">

    <form action="{% if artikel is not defined %}{{ path('artikel_create') }}{% else %}{{ path('artikel_update') }}{% endif %}"
          method="post" enctype="multipart/form-data">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Judul</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="judul" id="judul"
                       value="{% if artikel is defined %}{{ artikel.judul }}{% endif %}" placeholder="Tulis Judul" required id="judul_form">
            </div>
        </div>

        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Isi</label>
            <div class="col-sm-10">
                <textarea name="isi" placeholder="Isi" rows="5"
                          cols="100" required id="isi_form">{% if artikel is defined %}{{ artikel.isi }}{% endif %}</textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Jenis Artikel</label>
            <div class="col-sm-10">
                <select class="custom-select" id="jenis_form" name="jenis" required>
                    <option value="Hiburan" {% if artikel is defined and artikel.jenis == "Hiburan" %}selected{% endif %}>
                        Hiburan
                    </option>
                    <option value="Berita" {% if artikel is defined and artikel.jenis == "Berita" %}selected{% endif %}>
                        Berita
                    </option>
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Penulis</label>
            <div class="col-sm-10">
                <select class="custom-select" id="penulis_form" name="penulis" required>
                    {% for data in penulis %}
                        <option value="{{ data.id }}" {% if artikel is defined and artikel.getIdPenulis().id == data.id %}selected{% endif %}>{{ data.nama }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-2 pt-0">Lolos Edit</legend>
                <div class="col-sm-10">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="lolos_edit" id="lolos_edit1"
                               value="Lolos" required {% if artikel is defined and artikel.getLolosEdit() == 'Lolos' %}checked="checked"{% endif %}>
                        <label class="form-check-label" for="lolos_edit1">
                            Lolos
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="lolos_edit" id="lolos_edit0"
                               value="Tidak Lolos" required {% if artikel is defined and artikel.getLolosEdit() == 'Tidak Lolos' %}checked="checked"{% endif %}>
                        <label class="form-check-label" for="lolos_edit0">
                            Tidak Lolos
                        </label>
                    </div>
                </div>
            </div>
        </fieldset>
        {% if artikel is not defined %}
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Foto</label>
            <div class="col-sm-10">
                <input type="file" class="form-control-file" name="foto" id="foto_form" required>
            </div>
        </div>
        {% endif %}

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" {% if artikel is not defined %}onclick="tambah()"{% endif %} class="btn btn-primary">Simpan</button>
            </div>
        </div>
    </form>
</div>

templates/artikel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artikel{% endblock %}

{% block body %}
    <h1>Edit Artikel</h1>

    {{ include('artikel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('artikel_index') }}">back to list</a>
{% endblock %}

templates/artikel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artikel index{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Artikel index</h1>
            <a href="{{ path('artikel_new') }}">Create new</a>
            <div class="table-responsive">
                <table class="table table-hover table-bordered" id="datatable">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Judul</th>
                            <th>Isi</th>
                            <th>Jenis</th>
                            <th>Dilihat</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>{% set i=1 %}{% for artikel in artikels %}
                        <tr>
                            <td>{{ i }}{% set i=i+1 %}</td>
                            <td>{{ artikel.judul }}</td>
                            <td>{{ artikel.isi }}</td>
                            <td>{{ artikel.jenis }}</td>
                            <td>{{ artikel.counter }} kali</td>
                            <td>
                                <a href="{{ path('artikel_show', {'id': artikel.id}) }}" class="btn btn-primary"><i class="far fa-eye"></i></a>
                                <a href="{{ path('artikel_edit', {'id': artikel.id}) }}" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                                {{ include('artikel/_delete_form.html.twig') }}
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="8">no records found</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}

<script>
    $(document).ready(function () {
        $('#datatable').DataTable();
    }); 
</script>
{% endblock %}

templates/artikel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artikel Baru{% endblock %}

{% block body %}
    <h1>Buat Artikel</h1>

    {{ include('artikel/_form.html.twig') }}

    <a href="{{ path('artikel_index') }}">Kembali</a>
{% endblock %}

{% block javascript %}
function tambah() {
    event.preventDefault()

    var foto = $('#foto-form').val().split('\\').pop()
    var judul = $('#judul-form').val()
    var isi = $('#isi-form').val()
    var jenis = $('#jenis-form').val()
    var penulis = $('#penulis-form option:selected').val()
    var lolos_edit = $("input[name='lolos_edit1'||'lolos_edit0']:checked").val()

    if ((foto == '' || foto == null)) {
        alert('Gambar tidak boleh kosong')
    } else if (judul == '' || judul == null) {
        alert('Judul tidak boleh kosong')
    } else if (isi == '' || isi == null) {
        alert('isi tidak boleh kosong')
    } else if (jenis == '' || jenis == null) {
        alert('jenis wajib diisi')
    } else if (penulis == '' || penulis == null) {
        alert('Pilih salah satu penulis')
    } else if (lolos_edit == '' || lolos_edit == null) {
        alert('Pilih salah satu lolos edit')
    } else {
        $('#form').attr('action', '{{ path('artikel_create') }}')
                    $('#form').submit()
                }
            }
{% endblock %}

templates/artikel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artikel{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ path('artikel_index') }}" class="btn btn-primary"><i class="fas fa-arrow-left"></i></a>
            <a href="{{ path('artikel_edit', {'id': artikel.id}) }}" class="btn btn-primary"><i class="fas fa-edit"></i></a>
            {{ include('artikel/_delete_form.html.twig') }}
            <h1>Artikel</h1>

            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ artikel.id }}</td>
                    </tr>
                    <tr>
                        <th>Judul</th>
                        <td>{{ artikel.judul }}</td>
                    </tr>
                    <tr>
                        <th>Isi</th>
                        <td>{{ artikel.isi }}</td>
                    </tr>
                    <tr>
                        <th>Foto</th>
                        <td><img src="{{ asset(artikel.foto) }}" width="200px"></td>
                    </tr>
                    <tr>
                        <th>Jenis</th>
                        <td>{{ artikel.jenis }}</td>
                    </tr>
                    <tr>
                        <th>Lolos_edit</th>
                        <td>{{ artikel.lolosEdit }}</td>
                    </tr>
                    <tr>
                        <th>Penulis</th>
                        <td>{{ artikel.getIdPenulis().nama }}</td>
                    </tr>
                    <tr>
                        <th>Counter</th>
                        <td>{{ artikel.counter }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}